### ISSUE TITLE
Remove New Relic from peerDependencies

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-node#101]
Since NR is an optional part of this module, we shouldn't add it to `peerDependencies` because that incorrectly indicates that it's required and throws an npm warning on every project using this repo w/o the NR piece.

The warnings aren't _terrible_, but there are build scripts out there (such as those that come out of the box with `create-react-app`, I believe) that treat any warnings as errors when building for production, so this package breaks builds on projects that aren't using New Relic.

Instead of enforcing it programmatically, we should ensure the docs make that clear. We already have custom error handling if `newrelic` isn't installed, here:

https://github.com/Automattic/vip-go-node/blob/53ebaeb09139eeb3b76537ba95bdf93f537645e2/src/newrelic/index.js#L17-L23

**Comment by mjangda** [comment]
Should it be a an `optionalDependency` instead? https://docs.npmjs.com/files/package.json#optionaldependencies

**Comment by nickdaugherty** [comment]
I believe that will still attempt to install that package, which is not really what we want as NR is heavy and requires slow node-gyp compilation, which is unnecessary unless a project actually wants to track the app in NR.

**Comment by elazzabi** [comment]
New patch pushed to npm, `0.3.2` should have this change now.
