### ISSUE TITLE
Add preflight checks

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-node#112]
Possibly a script (e.g. `npx vip-go-preflight-checks`) that can be run to verify that the app meets all the necessary requirements to work smoothly on VIP Go.

**Comment by elazzabi** [comment]
Current list of requirements we can check:

1. `npm build` and `npm start` are present. We can also check that `npm serve` isn't present and raise a warning. In Create React App, `start` is used for dev, and `serve` for prod. Must not use a process monitor (like nodemon, PM2) to handle restarts, VIP Go takes care of this.
2. `@automattic/vip-go-node` is used and server is listening on `process.env.PORT`. We can check this by running the app with a PORT and pinging `GET /cache-healthcheck?` that should respond with `200 OK`
3. If using `redis`, make sure to use `REDIS_MASTER` and `REDIS_PASSWORD`. Waiting #110

**Comment by elazzabi** [comment]
fixed by #118
