### ISSUE TITLE
Discussion around removing winston

### ISSUE THREAD

**Issue by elazzabi** [Automattic/vip-go-node#128]
When we started this package, our first helper was the `logger` and thus, we introduced `winston` as a dependency to this package.

However, lot of our users are using the `server` or `newrelic` helpers and don't need `winston`

I suggest we move `winston` to a peerDependency or remove it all together and ask clients to install it explicitly

**Comment by elazzabi** [comment]
cc @mjangda & @nickdaugherty

**Comment by nickdaugherty** [comment]
What specific benefits do we get by removing Winston?

The only official (non-external) way to log from an App on Go is to use our log library, and allowing clients to install other versions of Winston could end up adding more complication / headache down the road as we'd need to ensure our logger works on all possible versions. 

A `peerDependency` isn't a good fit for the same reasons we quite using that for `newrelic` - it always will throw an npm warning on install if not present, and can actually cause builds to break even if the app isn't using it.

**Comment by elazzabi** [comment]
> What specific benefits do we get by removing Winston?

We were thinking [here](https://github.com/Automattic/vip-go-node/pull/118/files#r275628627) if it's a good idea to make this package a strict requirement instead of optional. And to do this, we need to make sure we add the dependencies we use only. For now it's `winston`, but with the upcoming `redis` helper, we'll be introducing yet another dependency (`redisio`) and we'll have some clients installing this even if they aren't using it.

I know it's hard to be compatible with all versions. This is why I started this issue, to see if there is something we can do to handle this better :)
