### ISSUE TITLE
Logger Dependencies Missing

### ISSUE THREAD

**Issue by mikeselander** [Automattic/vip-go-node#129]
The logger component requires `cluster` (which in turn requires `repl`), but the libraries are not required in either dependencies nor documented as required.

https://github.com/Automattic/vip-go-node/blob/04ca1072de079c8283e48aeda25606e58f27a5ed/src/logger/index.js#L2

**Comment by mjangda** [comment]
This is referencing the built-in Node cluster lib: https://nodejs.org/api/cluster.html

**Comment by mikeselander** [comment]
Right, of course - definitely missed that 🤦‍♂️ Our app is falling over when including this line so looks like I need to do some more digging.
