### ISSUE TITLE
Add ability to easily purge a single URL

### ISSUE THREAD

**Issue by GaryJones** [Automattic/vip-go-node#173]
## Expected/Desired Behavior

Add ability for apps to easily purge a URL from the VIP edge caches.

Something akin to [the `wpcom_vip_purge_edge_cache_for_url()` PHP function](https://github.com/Automattic/vip-go-mu-plugins/blob/da7fcd24b773e1957687c6eb56f0b56ddd402d9e/vip-cache-manager/api.php#L10-L12).

## Actual Behavior

Currently there is no support for purging a URL.

## Steps to Reproduce the Problem

Only workaround for now is to have a Node app call a WP app and use the above PHP function, or for the Node app to make the PURGE request directly, once the correct URLs and args have been established.

**Comment by simonwheatley** [comment]
Noted in JIRA as [GH-3331]

**Comment by mjangda** [comment]
@GaryJones can you share some example use cases where this would be used? That will help define what this API should look like.

**Comment by GaryJones** [comment]
One client who uses this package wanted to clear `/robots.txt`, since it was written as an actual robots.txt file, and served from Express with 30 days maxAge. When they had made a change to that file, the change didn't appear on the front end.

My thought was that there could be a way to call something that could purge a URL under a certain condition.

**Comment by chriszarate** [comment]
We have shipped a few different ways to purge page cache for Node.js applications:

https://docs.wpvip.com/how-tos/flush-the-page-cache/
