### ISSUE TITLE
preflight-checks: Make a copy of the app

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-node#176]
Rather than modifying the app in the current folder, make a copy of it (minus node_modules) and run the checks on that instead. This would avoid conflicts caused by the checks which can be frustrating or misleading.

**Comment by simonwheatley** [comment]
Noted in JIRA as [GH-3341]

**Comment by chriszarate** [comment]
Checks now run in a Docker container, so we can mark this as solved.
