### ISSUE TITLE
preflight-checks: Add VIP_GO_APP_ID env var when running checks

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-node#186]
## Expected/Desired Behavior

On the VIP environment, there is a `VIP_GO_APP_ID` environment available, which some apps make use of to detect the environment (and conditionally run builds, etc).

We need to emulate production as closely as possible.

## Actual Behavior

`VIP_GO_APP_ID` is not set, which means conditional logic in `package.json` and the apps themselves will behave differently in the preflight tests than they do in production.

## Steps to Reproduce the Problem

1. Have a `package.json` with a line like this: `"build": "if [ -z $VIP_GO_APP_ID ]; then npm run webpack; else exit 0; fi",`
1. Run the preflight tests
1. Note that the `npm run webpack` line tries to execute, when it wouldn't in production - this is the bug

**Comment by simonwheatley** [comment]
Noted in JIRA as [GH-3352]
