### ISSUE TITLE
Logging lib

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-node#2]
Currently we're using the `debug` package across our apps. However, Node apps on Go require the logging format to be very specific which is a bit harder to do with `debug`. It also doesn't support error levels so we'd need to add a wrapper library to add that functionality.

We should extend `winston` (or a similar library) with a custom transport that pipes to `stdOut` and matches the expected output by our Logstash parser.

We should also have a separate transport for local use as well (since JSON isn't very easy to read :)).

The logs need to be formatted as JSON with a specific set of fields. This allows the log parser to actually pick them up and we can them access them via Kibana.

See `src/logger/index.js` in the `happychat` repo for an example of what the output should look like.

**Comment by elazzabi** [comment]
Fixed by #6
