### ISSUE TITLE
JSON log format should be fully JSON

### ISSUE THREAD

**Issue by hanifn** [Automattic/vip-go-node#29]
I've noticed that the format for the JSON log is a mix of string text and JSON like so
```
// => The format is: <timestamp> <namespace> JSON
// => 2018-08-03T09:54:07.013Z application:application_type {"message":"This is a log from my application","level":"info","timestamp":"2018-08-03T09:54:07.013Z","app":"application","app_type":":application_type" // etc // }
```

But for almost all examples of JSON logging for logstash I've seen, the format is always fully JSON.
See the example JSON logs for use with logstash [here](https://github.com/sirupsen/logrus).

I think this makes sense as logstash would not need a custom parser to fish out the JSON part from the string text part. So to support better parsing and search on logstash, we should do the same as well.

See also [Extracting fields and Wrangling Data](https://www.elastic.co/guide/en/logstash/current/field-extraction.html)

**Comment by elazzabi** [comment]
There is a custom scrapper on VIP Go that scraps log files and push them to `logstash`. And the format it search for is the one we're using: `<timestamp> <namespace> JSON`

cc @mjangda for more info

**Comment by hanifn** [comment]
Ah cool . I didn't know this was already following a standardised format.
