### ISSUE TITLE
New Relic

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-node#3]
Easy interface for integrating New Relic APM: https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/install-nodejs-agent

**Comment by elazzabi** [comment]
The documentation suggests copying a configuration file from `node_modules` to the application **main folder**. This isn't the workflow we want as we can't be sure that we'll copy the file to the right directory and there will be problems with file system access...

We can skip this configuration file by setting environment variables and I guess this is the approach will be using.

They also say that the require should be the first line of the app main module. I need to test if it's actually the case or we can set some env variables before requiring it (it should work, I think)

cc @mjangda
