### ISSUE TITLE
Using string interpolation in log messages seems to break logging

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-node#36]
Example:

```
log.info( 'Testing string interpolation, %o', { some: 'fancy', object: { with: 'nested' } } );
```

The log file and logstash then get really confused and everything is jumbled. I haven't really dug into what's wrong here, but I think here is a good place to start looking:

https://github.com/Automattic/vip-go-node/blob/fe709f19a11392d3a7bbb525556fc60e82f986ee/src/logger/index.js#L28-L30

**Comment by nickdaugherty** [comment]
This needs more investigation / reproduction. I'm less convinced now that it's a bug than when I opened the issue...

**Comment by elazzabi** [comment]
I'll try to reproduce this. I guess we only test for string interpolation whereas that `%o` is used to interpolate an object, right?

https://github.com/Automattic/vip-go-node/blob/master/__tests__/logger.tests.js#L38

**Comment by nickdaugherty** [comment]
> I guess we only test for string interpolation whereas that %o is used to interpolate an object, right?

Ya that's right. I'm kind of thinking this is not actually the cause of the problem I'm seeing, but haven't come back to try again.

**Comment by nickdaugherty** [comment]
Going to close this out, not actually an issue.
