### ISSUE TITLE
Allow setting log transports globally

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-node#37]
It would be nice to have a way to globally set the transports, (overridable per-instance).

The main use-case that comes up is tests - during CI tests the logs should probably be disabled, but currently there isn't a way to do that without adding conditional transports to every instance of the logger.

**Comment by nickdaugherty** [comment]
Alternatively (or in addition to this), we can support disabling all logging with the `silent` option. Maybe we either default `silent` to `true` when `NODE_ENV=test`, or provide a way to set it globally.

https://github.com/winstonjs/winston#creating-your-own-logger

**Comment by elazzabi** [comment]
i'm totally with the `silent` option. looking at `winston` you can do it per logger, but we can also add a way to set it globally for all loggers.

for future, we can also pass all arguments we receive to `winston`. this way we'll have `winston`'s features out of the box

**Comment by elazzabi** [comment]
As discussed, it would be better if we let the client do what they want with the logger. The behavior of a global transport can be achieved by the following code (from @mjangda):

``` javascript
// logger.js file
const { logger } = require( '@automattic/vip-go' );

exports default ( namespace ) => {
  // SOME_TRANSPORT will be used as a transport for all future instances
  return logger( namespace, { transport: SOME_TRANSPORT }  );
}

// other files
const logger = require( './logger.js' );
logger( 'app:auth' );
logger.info( 'Something' );
```

**Comment by elazzabi** [comment]
@nickdaugherty I'll go and close this issue but feel free to re-open it if the explained method above ^ isn't enough

**Comment by nickdaugherty** [comment]
Alright, that should be sufficient for this (bit harder to setup but not too important).
