### ISSUE TITLE
Default uncaughtException handler

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-node#5]
If an app crashes with `uncaughtException` we need to make sure we log it.

If we add in cluster support (as noted in #4), the error message should include specifics around which worker caused the fatal.

**Comment by elazzabi** [comment]
What should we do after logging the event? `process.exit`? I'm sure eslint will not accept that

**Comment by mjangda** [comment]
> What should we do after logging the event? process.exit? I'm sure eslint will not accept that

Based on the docs, we can just log the error (and don't need to do anything else): https://nodejs.org/api/process.html#process_event_uncaughtexception
