### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-go-node#9]
- [x] Integrate [`publish-please`](https://github.com/inikulin/publish-please)
- [x] Package package on npm (`@Automattic/vip-go`)
- [x] Document the process (something similar to https://github.com/Automattic/vip/blob/master/CONTRIBUTING.md#releasing--publishing)

**Comment by mjangda** [comment]
@elazzabi I think we're good to publish v0.1 now.

**Comment by elazzabi** [comment]
@mjangda This is the command I was writing in my command line: `npm version minor`. I see that you can read minds... 😆

**Comment by mjangda** [comment]
This is done.
